### ISSUE TITLE
Can't start service on Ubuntu 16.04

### ISSUE THREAD

**Issue by daymansiege** [lmenezes/cerebro#358] opened 2019-04-11 08:13 UTC
Hello!

I've installed latest cerebro using DEB package:

```
lsb_release -a

OUTPUT:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

```
wget https://github.com/lmenezes/cerebro/releases/download/v0.8.3/cerebro_0.8.3_all.deb
sudo dpkg -i cerebro_0.8.3_all.deb

OUTPUT:
Selecting previously unselected package cerebro.
(Reading database ... 264609 files and directories currently installed.)
Preparing to unpack cerebro_0.8.3_all.deb ...
Unpacking cerebro (0.8.3) ...
Setting up cerebro (0.8.3) ...
Creating system group: cerebro
Creating system user: cerebro in cerebro with cerebro daemon-user and shell /bin/false
Created symlink from /etc/systemd/system/multi-user.target.wants/cerebro.service to /lib/systemd/system/cerebro.service.
```

Status says service is down:
```
sudo systemctl status cerebro

OUTPUT:
● cerebro.service - Elasticsearch web admin tool
   Loaded: loaded (/lib/systemd/system/cerebro.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-04-11 09:57:15 CEST; 51s ago
  Process: 23424 ExecStart=/usr/share/cerebro/bin/cerebro (code=exited, status=255)
  Process: 23421 ExecStartPre=/bin/chmod 755 /run/cerebro (code=exited, status=0/SUCCESS)
  Process: 23417 ExecStartPre=/bin/chown cerebro:cerebro /run/cerebro (code=exited, status=0/SUCCESS)
  Process: 23412 ExecStartPre=/bin/mkdir -p /run/cerebro (code=exited, status=0/SUCCESS)
 Main PID: 23424 (code=exited, status=255)

Apr 11 09:57:15 udv-elastic1 systemd[1]: cerebro.service: Unit entered failed state.
Apr 11 09:57:15 udv-elastic1 systemd[1]: cerebro.service: Failed with result 'exit-code'.
```

Service journal shows details that `./cerebro.db` can't be accessed:
```
sudo journalctl -u cerebro

OUTPUT:
Apr 11 09:58:15 udv-elastic1 systemd[1]: Starting Elasticsearch web admin tool...
Apr 11 09:58:15 udv-elastic1 systemd[1]: Started Elasticsearch web admin tool.
Apr 11 09:58:49 udv-elastic1 cerebro[23641]: Oops, cannot start the server.
Apr 11 09:58:49 udv-elastic1 cerebro[23641]: java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 30001ms.
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:57)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:136)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:114)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:129)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:94)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutions$.$anonfun$runEvolutions$1(ApplicationEvolutions.scala:177)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutions$.withLock(ApplicationEvolutions.scala:203)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutions$.runEvolutions(ApplicationEvolutions.scala:173)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1(ApplicationEvolutions.scala:53)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1$adapted(ApplicationEvolutions.scala:53)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at scala.collection.immutable.Stream.foreach(Stream.scala:533)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:53)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:85)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:51)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:50)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:41)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.Guice.createInjector(Guice.java:87)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.google.inject.Guice.createInjector(Guice.java:78)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:186)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:139)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.core.server.ProdServerStart$.start(ProdServerStart.scala:57)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]: Caused by: java.sql.SQLException: opening db: './cerebro.db': Permission denied
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at org.sqlite.core.CoreConnection.open(CoreConnection.java:203)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at org.sqlite.JDBC.createConnection(JDBC.java:114)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at org.sqlite.JDBC.connect(JDBC.java:88)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:119)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Apr 11 09:58:49 udv-elastic1 cerebro[23641]:         at java.lang.Thread.run(Thread.java:748)
Apr 11 09:58:49 udv-elastic1 systemd[1]: cerebro.service: Main process exited, code=exited, status=255/n/a
Apr 11 09:58:49 udv-elastic1 systemd[1]: cerebro.service: Unit entered failed state.
Apr 11 09:58:49 udv-elastic1 systemd[1]: cerebro.service: Failed with result 'exit-code'.
```

**Comment by Reiner030** [comment] 2019-04-12 19:02
Same with Debian Stretch/9.

The problem is easy to see - we have both same cause:

````
Apr 11 09:58:49 udv-elastic1 cerebro[23641]: Caused by: java.sql.SQLException: opening db: './cerebro.db': Permission denied
````

=> The file can't be created in working directory which is defined in service file:

````
# systemctl cat cerebro.service
# /lib/systemd/system/cerebro.service
[Unit]
Description=Elasticsearch web admin tool
Requires=network.target

[Service]
Type=simple
WorkingDirectory=/usr/share/cerebro
EnvironmentFile=/etc/default/cerebro
ExecStart=/usr/share/cerebro/bin/cerebro
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=60
SuccessExitStatus=143
TimeoutStopSec=5
User=cerebro
ExecStartPre=/bin/mkdir -p /run/cerebro
ExecStartPre=/bin/chown cerebro:cerebro /run/cerebro
ExecStartPre=/bin/chmod 755 /run/cerebro
PermissionsStartOnly=true
LimitNOFILE=1024

[Install]
WantedBy=multi-user.target
````
where only the run/cerebro folder is created and fixed with access rights.
But there is the folder /usr/share/cerebro missed... 

For my first test it was sufficient to chown the folder to cerebro.
Depended on needs there might be also subfolder updated ?

Best would be to to the right switch into the package; alternatively it could be addedd to service file:
````
ExecStartPre=/bin/chown cerebro:cerebro /usr/share/cerebro
#ExecStartPre=/bin/chmod 755 /usr/share/cerebro
````

Bests

**Comment by daymansiege** [comment] 2019-04-15 06:51
@Reiner030 thank you! It seems it worked!
I hope it will be included in next release :)

**Comment by moliware** [comment] 2019-04-16 08:24
I'll try how to fix it in the next release.

Thanks for the investigation!!

**Comment by ttimasdf** [comment] 2019-04-24 03:12
`/usr/share/cerebro` is the root directory of the program. It may not be the best practice to grant write permission for a system-wide installed application, IMHO. For me, I chown the directory and let cerebro create the database at its first run, and chown back to root afterwards. Maybe move the db file elsewhere is better?

**Comment by rtkgjacobs** [comment] 2019-04-24 12:41
Ideally the db should be in a folder such as `/var/lib/cerebro` - a folder owned by the cerebro user/group created that runs the service itself.

**Comment by moliware** [comment] 2019-05-22 15:09
So if your run `/usr/share/cerebro/bin/cerebro -Ddata.path=/var/lib/cerebro/cerebro.db` this should work. So editing the service file and replace the ExecStart should make it work.

Now I have to figure out how to configure the`ExecStart` from my build.sbt file so that the next release produce a .deb that works out of the box

**Comment by moliware** [comment] 2019-05-23 14:33
Now I know how to configure `ExecStart`. Since I don't have ubuntu / debian,  could anybody confirm that changing this like in `lib/systemd/system/cerebro.service`:

```ExecStart=/usr/share/cerebro/bin/cerebro```
to : 
```ExecStart=/usr/share/cerebro/bin/cerebro -Ddata.path=/var/lib/cerebro/cerebro.db```

makes it work. Thanks!

**Comment by walrusVision** [comment] 2019-05-28 05:15
Hey @moliware, I've tested that and its now working correctly.

**Comment by moliware** [comment] 2019-07-23 14:28
This should be fixed in version 0.8.4

**Closed by moliware** 2019-07-23 14:28 UTC

**Comment by Reiner030** [comment] 2019-09-30 19:25
Hello,
tested today version 0.8.4 on Debian Buster/10 and it fails again.

Problem: you need to coordinate the folders right ;)
* In service file work directory is setup to usr (= "static" data) folder: `WorkingDirectory=/usr/share/cerebro`
* home folder should be setup to `/usr/share/cerebro` folder so that is's not defaulting to `/home/cerebro`?
* In /etc/cerebro/application.conf you setup `data.path = "./cerebro.db"`
  which should be created in WorkingDirectory so it's actual wrong path `/usr/share/cerebro` but not in "var"iable path as in comment `"/var/lib/cerebro/cerebro.db"` if I am right - the initial database wasn't created.

Here the paths with the setup rights by package:
```
# ls -la /usr/share/cerebro /var/lib/cerebro/ ~cerebro/
ls: cannot access '/home/cerebro/': No such file or directory
/usr/share/cerebro:
total 32
drwxr-xr-x   5 root root  4096 Sep 30 19:09 .
drwxr-xr-x 140 root root  4096 Sep 30 19:09 ..
-rw-r--r--   1 root root  2932 Jul 23 11:59 README.md
drwxr-xr-x   2 root root  4096 Sep 30 19:09 bin
drwxr-xr-x   3 root root  4096 Sep 30 19:09 conf
drwxr-xr-x   2 root root 12288 Sep 30 19:09 lib
lrwxrwxrwx   1 root root    16 Jul 23 11:59 logs -> /var/log/cerebro

/var/lib/cerebro/:
total 8
drwxr-xr-x  2 cerebro cerebro 4096 Jul 23 11:59 .
drwxr-xr-x 40 root    root    4096 Sep 30 19:09 ..
```

Here the installed service file where you are changing the rights only on /run/cerebro folder for each start which is fine so far:
```
# systemctl cat cerebro.service
# /lib/systemd/system/cerebro.service
[Unit]
Description=Elasticsearch web admin tool
Requires=network.target

[Service]
Type=simple
WorkingDirectory=/usr/share/cerebro
EnvironmentFile=/etc/default/cerebro
ExecStart=/usr/share/cerebro/bin/cerebro
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=60
SuccessExitStatus=143
TimeoutStopSec=5
User=cerebro
ExecStartPre=/bin/mkdir -p /run/cerebro
ExecStartPre=/bin/chown cerebro:cerebro /run/cerebro
ExecStartPre=/bin/chmod 755 /run/cerebro
PermissionsStartOnly=true
LimitNOFILE=1024

[Install]
WantedBy=multi-user.target
```

**Comment by toddejohnson** [comment] 2019-11-20 05:21
Tested on 0.8.5 on CentOS7 and had similar fails as above. 

I'd suggest altering home to /var/lib/cerebro as above then fixing the unit to be

```
[Unit]
Description=Elasticsearch web admin tool
Requires=network.target

[Service]
Type=simple
WorkingDirectory=/var/lib/cerebro
EnvironmentFile=/etc/default/cerebro
ExecStart=/usr/share/cerebro/bin/cerebro -Ddata.path=/var/lib/cerebro/cerebro.db
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=60
SuccessExitStatus=143
TimeoutStopSec=5
User=cerebro
ExecStartPre=/bin/mkdir -p /run/cerebro
ExecStartPre=/bin/chown cerebro:cerebro /run/cerebro
ExecStartPre=/bin/chmod 755 /run/cerebro
PermissionsStartOnly=true
LimitNOFILE=1024

[Install]
WantedBy=multi-user.target
```
