### ISSUE TITLE
REST console output rounds `long` values

### ISSUE THREAD

**Issue by kutchar** [lmenezes/cerebro#233] opened 2017-11-24 23:18 UTC
If the results contain values of large long numbers, then those numbers get rounded.
`3167083603374929920` becomes `3167083603374930000`

Respone using curl:
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.1631508,
    "hits" : [
      {
        "_index" : "test-1",
        "_type" : "e",
        "_id" : "2apoqnnxESwAklIzu8xqB",
        "_score" : 1.1631508,
        "_source" : {
          "value" : 3167083603374929920
        }
      }
    ]
  }
}
```

Response using Cerebro's `rest` console:
```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index" : "test-1",
        "_type": "e",
        "_id": "2apoqnnxESwAklIzu8xqB",
        "_score": 1,
        "_source": {
          "value": 3167083603374930000
        }
      }
    ]
  }
}
```

**Comment by lmenezes** [comment] 2017-12-05 10:24
this is a duplicate of #228

**Closed by lmenezes** 2017-12-05 10:24 UTC
