### ISSUE TITLE
Cerebro with elasticsearch protected by xpack account - Error

### ISSUE THREAD

**Issue by iFedix** [lmenezes/cerebro#157] opened 2017-06-01 13:09 UTC
I really love this tool, very very useful. Unfortunately this does not work anymore to me :( I installed xpack and so protected the eleasticsearch indexes with an username and a password. So, when I connect to elasticsearch directly in the browser it asks me for the username and the password and then it shows me the normal info about the cluster:
`{
  "name" : "PincoPallino",
  "cluster_name" : "elastic",
  "cluster_uuid" : "4nqfFAkbRhmmXEvvjaivIA",
  "version" : {
    "number" : "5.4.0",
    "build_hash" : "780f8c4",
    "build_date" : "2017-04-28T17:43:27.229Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.0"
  },
  "tagline" : "You Know, for Search"
}
`
But when i put the url in cerebro an error pops up:  
`
Error while loading data 
{
  "error": "No handler found for uri [//_cluster/state/master_node,routing_table,routing_nodes,blocks] and method [GET]"
}`
I also tried by adding the authentication info in cerebro homepage but i receive the same error. Any help please?

**Comment by lmenezes** [comment] 2017-06-01 15:03
@iFedix I doubt this is really the problem, but I see **[//_cluster/state/master_node,routing_table,routing_nodes,blocks] and method [GET]" }**, where it seems there is one extra /(probably append to the ES host?). Could you try removing it and see what you get?

**Comment by iFedix** [comment] 2017-06-01 19:15
How to remove it? Where?

**Comment by iFedix** [comment] 2017-06-05 07:03
@Imenezes How to remove it? Where?

**Comment by iFedix** [comment] 2017-06-05 07:04
@Imenezes How to remove it? Where?

**Comment by moliware** [comment] 2019-04-04 14:23
He meant that when you connect to a host in cerebro, if you put 'http://your-es-server:9200/' (with the trailing `/`) this might be the issue. You should try without the trailing `/`. 

I close this, as the issue is old. If this is still an issue please reopen it.

Thanks!

**Closed by moliware** 2019-04-04 14:23 UTC
