### ISSUE TITLE
Allow to change baseUrl

### ISSUE THREAD

**Issue by champtar** [lmenezes/cerebro#84] opened 2017-03-01 19:06 UTC
Hi,

I like to have all my interface on the same host/port (kibana/grafana)
Currently I can set ```play.http.context="/cerebro/"``` in the config,
but ```buildBaseUrl()``` (js function) is not really working in this case

Thanks
Etienne

**Comment by lmenezes** [comment] 2017-03-01 21:29
duplicate of #48

**Closed by lmenezes** 2017-03-01 21:29 UTC
