### ISSUE TITLE
Tooltips missing and some suggestions

### ISSUE THREAD

**Issue by raulk89** [lmenezes/cerebro#75] opened 2017-02-17 11:36 UTC
Cerebro 0.5.1
Elastic 5.2.1

1. No tooltips in overview page, for example:
"**disable shard allocation**", "**extended node view**", "**sort...**", ""
Also heap, disk, cpu and load has no tooltips
Also cluster, "x nodes", "x indices", "x shards", "total docs.."... the whole row basically has no tooltips..
(at least kopf had all these tooltips)

2. Page snapshot "**show special indices**" tick does not work..

3. Shouldn't there be some page, where there is some node specific stats in tabular view (like when clicking to node name in cerebro). Meaning cpu, load, memory, disk, etc... 
Also some graphs would be nice. Basically like HQ plugin has node stats in tabular view + graphs.

4. Owerall, I would say that on screen there are a lot of wasted space, everything is streched according to your screen size, but specific pages would seem a lot nicer if not streched, for example "**cat apis**", "**snapshot**", "**repositories**",...

![cat apis](https://cloud.githubusercontent.com/assets/25365468/23063923/d11f37f8-f515-11e6-8e75-1a8c2d0ac470.JPG)

**Comment by lmenezes** [comment] 2017-02-20 21:24
hey @raulk89 
thanks for the feedback. 

At the moment I have very limited time to invest in cerebro, so there isn't so much care to aesthetic issues like components stretching over the whole screen.

I do take notice of issue number 2.

**Comment by lmenezes** [comment] 2017-03-11 17:12
duplicate of #89

**Closed by lmenezes** 2017-03-11 17:12 UTC
