### ISSUE TITLE
Windows 2012R2/2016 - LOAD Column

### ISSUE THREAD

**Issue by Lukiido** [lmenezes/cerebro#206] opened 2017-09-27 15:40 UTC
Hey All,

I have looked through everything I can think of, and no matter what i do the load section under nodes doesn't appear to populate any information. When I use the docker image it does populate, wondering if it is simply something I overlooked?

**Comment by lmenezes** [comment] 2017-09-29 13:02
in which setup is this happening? A local ES cluster with cerebro running also locally? If so, could you tell me the output of running these calls against your node(from the same place where cerebro is running):
```
/_nodes/_all/jvm,os
/_nodes/stats/jvm,fs,os,process
```

**Comment by Lukiido** [comment] 2017-10-03 13:26
It is a local ES cluster running Cerebro, Cerebro is on the 2012R2 node we have in the cluster which is our snapshot storage node. The 3 coordinator nodes, 3x Master, and 3x Data nodes are all running on windows server 2016.

[jvm,fs,os,process.txt](https://github.com/lmenezes/cerebro/files/1352412/jvm.fs.os.process.txt)
[jvm,os.txt](https://github.com/lmenezes/cerebro/files/1352413/jvm.os.txt)

**Comment by lmenezes** [comment] 2017-10-03 14:46
Hum, I'm not really sure what the issue is, but the responses you sent me do not contain the load information, so its not surprising that this is not shown on cerebro.

But you mentioned this was populated when running cerebro through the docker image?

**Comment by Lukiido** [comment] 2017-10-03 14:55
Yes so we have 2 different application both running their own elastic search clusters and installs, one is on redhat linux in a containerized environment, while the other is on windows install as a service and cerebro running via the bat file. 

Ive compared everything I can think of and it all appears to be configured the same, same settings etc the only difference is the environments themselves.

**Comment by lmenezes** [comment] 2017-10-03 14:58
yep, I think the environment is exactly the problem. I haven't looked, but it seems that for whatever reason, windows won't report the load on ES.

I will close this as there is nothing I can do, sorry  :(

**Closed by lmenezes** 2017-10-03 14:58 UTC
