### ISSUE TITLE
Performance on large clusters

### ISSUE THREAD

**Issue by tomsommer** [lmenezes/cerebro#208] opened 2017-10-04 08:13 UTC
I run a 14 node, 41242 shard, 2269 indexes cluster, and the Cerebro UI is horribly slow, as is the AJAX request for `/cluster_changes`, `/navbar` and `/overview`.

Is there any tricks to improving performance with this amount of indexes and shards? It seems like a mix of UI/rendering problems, but most of all the backend requests doesn't seem to be optimized for these large setups.

**Comment by yoann-bellet** [comment] 2017-10-05 07:45
Hello, I had the same problem, I was forced to rollback on 0.6.5.

**Comment by lmenezes** [comment] 2017-10-05 07:56
@yoann-bellet 0.6.5 works for you, but not newer releases?

**Comment by tomsommer** [comment] 2017-10-05 08:23
Same problem in 0.6.5, but "Only show affected" doesn't work in latest.

**Comment by yoann-bellet** [comment] 2017-10-05 11:56
@lmenezes  I had cerebro 0.6.5 on production, yesterday I put 0.6.8, and cerebro UI was very slow, on overview I had only names of nodes during 30 sec and impossible to switch between overview and nodes view,  So I rollback.

Cluster : 
ES 5.5.0 
3 Master, 11Workers, 2k5 idx, 28k shards, 66TB data

**Comment by yoann-bellet** [comment] 2017-10-05 11:59
But on 0.6.5, the filter indices was already not working (freeze of web browser)

**Comment by lmenezes** [comment] 2017-10-05 12:40
To be honest, I never tested the performance of the app for such extreme cases(I have several smaller clusters with few dozen indices on each), but I did not expect to be any differences between 0.6.5 and 0.6.8.

Could any of you do me a big favor and also try 0.6.6 and 0.6.7? I just want to pinpoint where the issue came from. 

I will try recreating this scenario locally to see what I can find.

Regarding the overall problem for clusters with so many indices/shards: this is feasible but it would be a very big change. At the moment, I just fetch all indices/nodes/allocation data for everything, and all filtering/pagination and so on is done on the frontend.

Changing that so I only request shard data for the relevant indices, might be a though one and also prone to errors(like indices changing between request for fetching indices and request to fetch data for these indices.

But I will give it a go.

**Comment by tomsommer** [comment] 2017-10-05 12:59
This has been a long time issue for me, so it's not since 0.6.5 for me.

The problem is also that ajax requests build up, because you run the requests every x amount of seconds, even if a reply takes 30+ seconds.

**Comment by lmenezes** [comment] 2017-10-05 13:08
Well, realistically I'm not so sure how to proceed here. If refresh interval is Xs, but requests take 5x that, things are bound to go wrong. But one thing is true: if requests takes long than refresh, these should at least be cancelled(although this will create the problem that, you might just not see anything until you increase the refresh interval). Thoughts on this?

**Comment by tomsommer** [comment] 2017-10-05 13:11
That won't work, what should happen is that no new requests should be made while waiting for an identical existing one.

**Comment by Programie** [comment] 2017-10-06 09:46
I'm having the same issue with a large cluster (~35.000 shards, ~4000 indices, ~30 nodes).

The only problem seems to be the /overview request which takes around 3 minutes. The /navbar request takes less than a second to respond and even the /cluster_changes request completes ~10 seconds.

The /overview endpoint seems to return each shard for each index. Is that really required? Could the performance be improved by only returning information for the currently visible indices?

**Comment by lmenezes** [comment] 2017-10-06 10:04
@Programie This would indeed improve performance a lot. But unfortunately, after evaluating how much code I would have to change for this to work, I have to say its not something I have time to do now, or likely ever.

Last night I took a look at how I could improve the overall performance for this, and found a way to hopefully make it faster. I hope to have a beta version for testing over the weekend and would love to get feedback from all of you on how much difference it actually makes.

**Comment by lmenezes** [comment] 2017-10-13 10:33
hey, I've just published v0.7.0, which tries to address issues with bigger clusters. 

In short, I optimised the way data was parsed/retrieved on the APIs, enabled gzip(which should help when downloading data for such big clusters) and now avoids re-requesting data if the previous request is still on-going.

Could you all let me know how this works? For my test data, response time dropped by more than half(which wasn't as slow as what you guys reported, although the size was quite similar).

**Comment by tomsommer** [comment] 2017-10-13 10:46
The load and disk indicators are broken :)

**Comment by Programie** [comment] 2017-10-13 10:50
I just tested the latest release.

I can confirm, the load times are much better, but in my case the /overview request still takes about 40 seconds. And it also heavily increases the load on the node.

**Comment by lmenezes** [comment] 2017-10-13 15:05
@tomsommer Not really broken... for the time being they are no longer a "progress bar", as after the changes I no longer have all the information I need to do so. My idea is to send elasticsearch a few PRs to try and solve a few issues I found while doing this. 

Did you test how the change affected response times for your cluster?

**Comment by lmenezes** [comment] 2017-10-13 15:08
@Programie I'm afraid I won't be able to do much more than that for now, as requesting shard information only for the visible nodes would be a much bigger change than what I can tackle atm.

I will increase the default refresh rate though.

On different topic, and I realise this might not be possible for everyone and all use cases, but having that many indices/shards on a single cluster might not be optimal. But I guess you know that already :)

**Comment by lmenezes** [comment] 2017-10-13 16:40
Ok... I have investigated a bit further, and the changes I made might have been a mistake. Using the _cat apis, although more convenient for parsing, are actually way slower/harder on the cluster: in general, the _cat apis execute more than one request sequentially(and sometimes the same request for different cat apis).

Some of the changes done were good, but the overall situation can still be improved without going all the way to requesting only shard information for the visible indices. I will try to find time to work on it during the next week. 

I will likely revert most of the changes and leave only the minor improvements, and start from scratch again.

**Comment by pyloor** [comment] 2017-10-16 02:14
Hi,
I run a 20 Node Cluster with 100 TB of data and approx 3000 shards. Last i ran the 0.6.7 version and hadn't any issues. With 0.7.0 everything runs smoothly. But i dont use the refreshes below 30secs. Thanks for your great work.

**Comment by lmenezes** [comment] 2017-10-17 17:19
ok... 0.7.1 is out, and for my own tests response time dropped to around 25% of the original base line. Let me know how this works out.

@tomsommer The load and disk indicators are also back to normal

**Comment by lmenezes** [comment] 2017-10-21 10:24
@tomsommer @Programie @yoann-bellet @pyloor any feed back on this? I'm really looking forward to close this issue.

**Comment by yoann-bellet** [comment] 2017-10-23 09:40
Hi @lmenezes, I tested 0.7.1, it's definitely better concerning performance for loading overview page, or node page (switching between them really works well now)
Concerning filtering by indices, it still make me crashing my browser if I use it

**Comment by lmenezes** [comment] 2017-10-23 11:23
@yoann-bellet which browser are you using? Will try to reproduce this locally and see what happens. 
This happens only when filtering the indices, right? Any special content, like RegExp or something? Or just plain text?

**Comment by yoann-bellet** [comment] 2017-10-23 11:34
Webbrowser ; Firefox 45.3.0
Yes it happend only on filtering indice on plain text (at first letter), browser become unresponding 

Cluster : 
ES 5.5.0
MN -> 3
WN -> 13
Volume -> 3355 idx, 39k shards, 86TB data

**Comment by Programie** [comment] 2017-11-13 11:33
Sorry for the delay. I've just tested version 0.7.1. In my case requests to /overview are now responding in around 10 to 15 seconds which is much better than before (~40 seconds).

**Comment by Programie** [comment] 2017-11-14 10:50
I just saw, that your previous fix to avoid re-requesting data if the previous request is still on-going is not existing in the current version anymore? At least in the current version (0.7.1), if a request to /overview takes longer than the configured refresh interval, there are two (or more) /overview requests waiting for a response.

**Comment by meersjo** [comment] 2017-11-22 11:39
Not particularly helpful as such; but I just upgraded from 0.6.1 to 0.7.1 this week, and still noticed considerably slower initial display of the indices - enough to make me go look if this version no longer supported elastic 5.2.

I just did a test on a 2-node cluster with 919 incides / 9190 shards; fresh Chrome window, stopwatched from <enter> in the address bar (with server in url) to index display:
0.6.1 took 10.94 seconds
0.7.1 took 28.15 seconds

**Comment by melvynator** [comment] 2017-11-27 09:32
@tomsommer You shouldn't have so many shards in your cluster. It's in average 20 shards per indice which is too much. I think you are over sharding.

**Comment by tomsommer** [comment] 2017-11-27 09:34
@melvynator Not really, since I have 14 nodes, and maybe 20 at some point (so one shard per node) - but I hear what you are saying.

**Comment by meersjo** [comment] 2017-11-27 11:18
That depends on the number of copies, @melvynator - @tomsommer  could have 4 copies of 5 shards per index, either for extreme redundancy, read performance and/or stretched-cluster performance.

**Comment by lmenezes** [comment] 2017-11-28 14:21
I'm closing this for now, as it seems the situation has improved considerably(and improving it further requires an amount of time I currently cannot invest).

**Closed by lmenezes** 2017-11-28 14:21 UTC
